# Generated by Django 4.2 on 2025-02-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMarket',
            fields=[
                ('test_market_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('test_market_location', models.CharField(max_length=50)),
                ('test_market_manager', models.CharField(max_length=50)),
                ('test_market_tell', models.CharField(max_length=50)),
                ('test_market_open', models.DateField(auto_now_add=True)),
                ('test_market_staff', models.IntegerField()),
            ],
        ),
    ]
