# Generated by Django 4.2 on 2025-02-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_stock', models.IntegerField()),
                ('test_market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='test_market.testmarket')),
            ],
        ),
    ]
